export { default as getAllContacts } from './getAllContacts'
export { default as getOneContact } from './getOneContact'
export { default as postContact } from './postContact'
export { default as deleteContact } from './deleteContact'
export { default as putContact } from './putContact'
export { default as updateStatusContact } from './updateStatusContact'
